### ISSUE TITLE
[Feature request] Make the text of code link editable

### ISSUE THREAD

**Issue by maxschulz-COL** [py-cafe/mkdocs-pycafe#1]
Essentially allow users to control: https://github.com/py-cafe/mkdocs-pycafe/blob/50f595900a4270e5ffb7369020282d98ae67a616/src/mkdocs_pycafe/__init__.py#L48

Ideally with emojis ;)

**Comment by maxschulz-COL** [comment]
This is now a lot less imortant after merge of #2 - will leave open but also happy to close it

**Comment by maartenbreddels** [comment]
Ah yes, I think it solves it actually. What is still missing ?

**Comment by maxschulz-COL** [comment]
> Ah yes, I think it solves it actually. What is still missing ?

I suppose making it editable, not just better, but that's more a general feature that is now a lot less important (to me at least). Or did I miss that one can edit it?

**Comment by maartenbreddels** [comment]
Yea, it is editable now https://mkdocs.py.cafe/en/latest/#code-block-with-a-link-to-pycafe

**Comment by maxschulz-COL** [comment]
> Yea, it is editable now https://mkdocs.py.cafe/en/latest/#code-block-with-a-link-to-pycafe

Ah sorry, you are completely correct!
